const actionTypes = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  BUY: 'BUY',
  SELL: 'SELL',
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
  SET_ERROR: 'SET_ERROR',
  RESET_ERROR: 'RESET_ERROR',
  HISTORY_RECORD: 'HISTORY_RECORD',
  GET_WALLET_INFO_REQUESTED: 'GET_WALLET_INFO_REQUESTED',
  GET_WALLET_INFO_RECEIVED: 'GET_WALLET_INFO_RECEIVED',
  GET_WALLET_INFO_REJECTED: 'GET_WALLET_INFO_REJECTED',
};

export default actionTypes;
